version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
        image: jareddjenkins/aspenleaf:dev
        ports:
            - 80:80
            - 443:443
    api:
        image: jareddjenkins/aspenleafapi:dev
        ports:
            - 8080:80
            - 8443:443

    sql:
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Strong!Passw0rd
        volumes:
            - mssql:/var/opt/mssql
volumes:
    mssql: